# Copyright (C) 2017 NVIDIA Corporation.  All rights reserved.
# Licensed under the CC BY-NC-ND 4.0 license (https://creativecommons.org/licenses/by-nc-nd/4.0/legalcode).
train:
  snapshot_save_iterations: 5000 # How often do you want to save trained models
  image_save_iterations: 500 # How often do you want to save output images during training
  display: 20 # How often do you want to log the training stats
  snapshot_prefix: ../outputs/celeba_eyeglasses_blond_hair_quadro/celeba_eyeglasses_blond_hair_quadro # Output
  #snapshot_prefix_b: ../outputs/celeba_eyeglasses_OFF_blond_hair_SWITCH/celeba_eyeglasses_OFF_blond_hair_SWITCH
  #snapshot_prefix_c: ../outputs/celeba_eyeglasses_SWITCH_blond_hair_OFF/celeba_eyeglasses_SWITCH_blond_hair_OFF
  snapshot_prefix_b: ../outputs/celeba_eyeglasses_blond_hair_quadro/try_b
  snapshot_prefix_c: ../outputs/celeba_eyeglasses_blond_hair_quadro/try_c
  hyperparameters:
    gen: CoVAE
    dis: CoDis
    vae_enc_w: 1.0e-05  # weight on the KL divergence loss
    vae_ll_w: 1.0e-04   # weight on the L1 reconstruction loss
    gan_w: 1.0          # weight on the adversarial loss
    quadro_w: 2.0e-04   # weight on the L1 a->b->d and a->c->d similarity
    batch_size: 16      # image batch size per domain
    ch: 64              # base channel number per layer
    max_iterations: 500000 # maximum number of training epochs
  datasets:
    a: # Domain 1 dataset
      channels: 3       # RGB -> 3 channels, Grayscale -> 1 channel
      image_size: 128   # crop image size, make sure it is power 2 and smaller than the image
      scale: 0          # Scale image or not. O -> no scaling
      class_name: dataset_image # dataset class
      root: ../datasets/celeba/ # dataset root location
      folder: img_align_crop_resize_celeba/ # image folder path relative to root
      list: lists/Eyeglasses_OFF_Blond_Hair_OFF.txt # image list path relative to root
    b: # Domain 2 dataset
      channels: 3
      image_size: 128
      scale: 0
      class_name: dataset_image
      root: ../datasets/celeba/
      folder: img_align_crop_resize_celeba/
      list: lists/Eyeglasses_OFF_Blond_Hair_ON.txt
    c: # Domain 2 dataset
      channels: 3
      image_size: 128
      scale: 0
      class_name: dataset_image
      root: ../datasets/celeba/
      folder: img_align_crop_resize_celeba/
      list: lists/Eyeglasses_ON_Blond_Hair_OFF.txt


